# Default Robotic Park Formation Control Benchmark

Operation:
  mode: virtual     # physical, virtual, hybrid
  tool: Webots              # Gazebo, Webots
  world: ControlFormation07.wbt 

Experience:
  type: reconfiguration

Architecture: 
  mode: distributed   # centralized, distributed_ros2, distributed
  node: 
    executable: none
    name: none
    pkg: none
    period: 0.0
    file: file.yaml

CPU_Monitoring: 
  enable: True
  node: 
    executable: measure_process
    name: benchmark
    pkg: measure_process_ros2_pkg
  processes: webots-bin, driver, ros2, swarm_driver, rviz2, swarm_reconfigu, supervisor_node

Interface: 
  enable: True
  rviz2: 
    enable: True
    node: 
      executable: rviz2
      name: rviz2
      pkg: rviz2
    file: ControlFormation07_reconfiguration.rviz
  rqt: 
    enable: True
    node: 
      executable: rqt_gui
      name: interface
      pkg: rqt_gui
    file: ControlFormation07.perspective
  own: 
    enable: False
    node:
      name:
      pkg:
    file:

Data_Logging: 
  enable: False
  all: True
  name: date
  topics: /ros2_cpu /cpu_stats 

Robots:
  Robot01:
    type: virtual
    name: dron01
    control_mode: HighLevel
    positioning: Intern
    pose: 2.54, -0.03, 0.70
    uri: radio://0/80/2M/E7E7E7E701
    controller:
      type: pid
      enable: True
      protocol: Continuous
      period: 0.01
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    data_attitude:
      enable: False
      T: 20
    data_rate: 
      enable: False
      T: 20
    data_motor: 
      enable: False
      T: 20
    data:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: gradient
        protocol: Continuous
        period: 0.1
        upperLimit: 0.1
        lowerLimit: -0.1
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron02_1.4107, dron05_1.4107, dron06_1.2267, origin_1.0

  Robot02:
    type: virtual
    name: dron02
    control_mode: HighLevel
    positioning: Intern
    pose: 0.80, 2.35, 0.70
    uri: radio://0/80/2M/E7E7E7E702
    controller:
      type: pid
      enable: True
      protocol: Continuous
      period: 0.01
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    data_attitude:
      enable: False
      T: 20
    data_rate: 
      enable: False
      T: 20
    data_motor: 
      enable: False
      T: 20
    data:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: gradient
        protocol: Continuous
        period: 0.1
        upperLimit: 0.1
        lowerLimit: -0.1
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron01_1.4107, dron03_1.4107, dron06_1.4787, dron07_1.6723, origin_1.0

  Robot03:
    type: virtual
    name: dron03
    control_mode: HighLevel
    positioning: Intern
    pose: -2.06, 1.44, 0.70
    uri: radio://0/80/2M/E7E7E7E703
    controller:
      type: pid
      enable: True
      protocol: Continuous
      period: 0.01
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    data_attitude:
      enable: False
      T: 20
    data_rate: 
      enable: False
      T: 20
    data_motor: 
      enable: False
      T: 20
    data:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: gradient
        protocol: Continuous
        period: 0.1
        upperLimit: 0.1
        lowerLimit: -0.1
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron02_1.4107, dron04_1.4107, dron07_1.3012, origin_1.0

  Robot04:
    type: virtual
    name: dron04
    control_mode: HighLevel
    positioning: Intern
    pose: -2.08, -1.45, 0.70
    uri: radio://0/80/2M/E7E7E7E704
    controller:
      type: pid
      enable: True
      protocol: Continuous
      period: 0.01
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    data_attitude:
      enable: False
      T: 20
    data_rate: 
      enable: False
      T: 20
    data_motor: 
      enable: False
      T: 20
    data:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: gradient
        protocol: Continuous
        period: 0.1
        upperLimit: 0.1
        lowerLimit: -0.1
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron03_1.4107, dron05_1.4107, dron07_1.3012, origin_1.0

  Robot05:
    type: virtual
    name: dron05
    control_mode: HighLevel
    positioning: Intern
    pose: 0.80, -2.41, 0.70
    uri: radio://0/80/2M/E7E7E7E705
    controller:
      type: pid
      enable: True
      protocol: Continuous
      period: 0.01
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    data_attitude:
      enable: False
      T: 20
    data_rate: 
      enable: False
      T: 20
    data_motor: 
      enable: False
      T: 20
    data:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: gradient
        protocol: Continuous
        period: 0.1
        upperLimit: 0.1
        lowerLimit: -0.1
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron01_1.4107, dron04_1.4107, dron06_1.4787, dron07_1.6723, origin_1.0

  Robot06:
    type: virtual
    name: dron06
    control_mode: HighLevel
    positioning: Intern
    pose: 0.91, -0.05, 0.70
    uri: radio://0/80/2M/E7E7E7E706
    controller:
      type: pid
      enable: True
      protocol: Continuous
      period: 0.01
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    data_attitude:
      enable: False
      T: 20
    data_rate: 
      enable: False
      T: 20
    data_motor: 
      enable: False
      T: 20
    data:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: gradient
        protocol: Continuous
        period: 0.1
        upperLimit: 0.1
        lowerLimit: -0.1
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron01_1.2267, dron02_1.4787, dron05_1.4787, dron07_0.82246, origin_1.0
  
  Robot07:
    type: virtual
    name: dron07
    control_mode: HighLevel
    positioning: Intern
    pose: -0.87, -0.01, 0.70
    uri: radio://0/80/2M/E7E7E7E707
    controller:
      type: pid
      enable: True
      protocol: Continuous
      period: 0.01
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    data_attitude:
      enable: False
      T: 20
    data_rate: 
      enable: False
      T: 20
    data_motor: 
      enable: False
      T: 20
    data:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: gradient
        protocol: Continuous
        period: 0.1
        upperLimit: 0.1
        lowerLimit: -0.1
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron02_1.6723, dron03_1.3012, dron04_1.3012, dron05_1.6723, dron06_0.82246, origin_1.0

Supervisor:
  enable: True
  node: 
    executable: supervisor_node
    name: supervisor
    pkg: mars_supervisor_pkg
    file: reconfiguration_topics.yaml

Other:
  Reconfiguration:
    enable: True
    executable: swarm_reconfiguration
    name: reconfiguration_node
    pkg: uned_swarm_task
    file: ControlFormation07_reconfiguration.yaml

