# Robotic Park Lagrange Multipliers Formation Control. Agents: 12

Operation:
  mode: virtual     # physical, virtual, hybrid
  tool: Webots              # Gazebo, Webots
  world: IROS_AffineFormation_N05.wbt 

Experience:
  type: herding           # identification, formation, navigation

Architecture: 
  mode: centralized   # centralized, distributed_ros2, distributed
  node: 
    executable: affine_formation_node
    name: formation_controller
    pkg: multi_agent_pkg

CPU_Monitoring: 
  enable: True
  node: 
    executable: measure_process
    name: benchmark
    pkg: measure_process_ros2_pkg
  processes: webots-bin, driver, ros2, swarm_driver, rviz2

Interface: 
  enable: True
  rviz2: 
    enable: True
    node: 
      executable: rviz2
      name: rviz2
      pkg: rviz2
    file: IROS_AffineFormation_N05.rviz
  rqt: 
    enable: True
    node: 
      executable: rqt_gui
      name: interface
      pkg: rqt_gui
    file: IROS_Formation.perspective
  own: 
    enable: False
    node:
      name:
      pkg:
    file:

Data_Logging: 
  enable: False
  all: False
  name: date
  topics: /ros2_cpu /cpu_stats /swarm/order /swarm_driver_cpu /swarm/status /driver_cpu /rviz2_cpu /webots_bin_cpu /current_theta /dist_sp /dron01/local_pose /dron01/local_pose_gt /dron01/target_pose /dron01/global_error /dron01/local_twist /dron02/local_pose /dron02/local_pose_gt /dron02/target_pose /dron02/global_error /dron02/local_twist /dron03/local_pose /dron03/local_pose_gt /dron03/target_pose /dron03/global_error /dron03/local_twist /dron04/local_pose /dron04/local_pose_gt /dron04/target_pose /dron04/global_error /dron04/local_twist /dron05/local_pose /dron05/local_pose_gt /dron05/target_pose /dron05/global_error /dron05/local_twist /khepera01/local_pose /khepera01/local_pose_gt /khepera01/target_pose /khepera01/global_error /khepera01/local_twist  

Robots:
  Robot01:
    type: virtual
    name: dron01
    positioning: Intern
    pose: 0.00, 1.00, 0.88
    uri: radio://0/80/2M/E7E7E7E701
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 50
    local_twist:
      enable: True
      T: 50
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: affine_p
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: herder
      type: herding
      relationship: dron02_1.1756, dron05_1.1756, khepera_1.0

  Robot02:
    type: virtual
    name: dron02
    positioning: Intern
    pose: 0.40, 0.91, 0.88
    uri: radio://0/80/2M/E7E7E7E702
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 50
    local_twist:
      enable: True
      T: 50
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: affine_p
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: herder
      type: herding
      relationship: dron01_1.1756, dron03_1.1756, khepera_1.0

  Robot03:
    type: virtual
    name: dron03
    positioning: Intern
    pose: 0.78, 0.62, 0.88
    uri: radio://0/80/2M/E7E7E7E703
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 50
    local_twist:
      enable: True
      T: 50
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: affine_p
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: herder
      type: herding
      relationship: dron02_1.1756, dron04_1.1756, khepera_1.0
      
  Robot04:
    type: virtual
    name: dron04
    positioning: Intern
    pose: 0.98, 0.18, 0.88
    uri: radio://0/80/2M/E7E7E7E704
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 50
    local_twist:
      enable: True
      T: 50
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: affine_p
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: herder
      type: herding
      relationship: dron03_1.1756, dron05_1.1756, khepera_1.0
      
  Robot05:
    type: virtual
    name: dron05
    positioning: Intern
    pose: 0.95, -0.28, 0.88
    uri: radio://0/80/2M/E7E7E7E705
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 50
    local_twist:
      enable: True
      T: 50
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: False
      controller:
        type: affine_p
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.1
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: herder
      type: herding
      relationship: dron04_1.1756, dron01_1.1756, khepera_1.0
      
  Robot06:
    type: virtual
    name: khepera01
    positioning: Intern
    pose: 0.00 0.00 0.00
    control_mode: HighLevel
    agent_ip: '192.168.0.21'
    port_number: 50000
    controller:
      type: ipc
      enable: True
      protocol: Continuous
      period: 0.01
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 50
    local_twist:
      enable: True
      T: 50
    data:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: reactive
        protocol: Continuous
        period: 0.05
        upperLimit: 0.1
        lowerLimit: -0.1
        gain: 0.2
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: herd
      type: reactive
      relationship: dron01_1.0, dron02_1.0, dron03_1.0, dron04_1.0, dron05_1.0
      
Supervisor:
  enable: True
  node: 
    executable: supervisor_node
    name: supervisor
    pkg: mars_supervisor_pkg
    file: IROS_AffineFormation_topics.yaml

Other:
  Agent00:
    enable: False
