# Robotic Park Lagrange Multipliers Formation Control. Agents: 12

Operation:
  mode: virtual     # physical, virtual, hybrid
  tool: Webots              # Gazebo, Webots
  world: LagrangeMultipliers_cone_N12.wbt 

Experience:
  type: formation           # identification, formation, navigation

Architecture: 
  mode: distributed   # centralized, distributed_ros2, distributed
  node: 
    executable: centralized_formation_controller
    name: formation_controller
    pkg: uned_swarm_task

CPU_Monitoring: 
  enable: True
  node: 
    executable: measure_process
    name: benchmark
    pkg: measure_process_ros2_pkg
  processes: webots-bin, driver, ros2, swarm_driver, rviz2

Interface: 
  enable: True
  rviz2: 
    enable: True
    node: 
      executable: rviz2
      name: rviz2
      pkg: rviz2
    file: LagrangeMultipliers_cone_N12.rviz
  rqt: 
    enable: False
    node: 
      executable: rqt_gui
      name: interface
      pkg: rqt_gui
    file: 
  own: 
    enable: False
    node:
      name:
      pkg:
    file:

Data_Logging: 
  enable: False
  all: False
  name: date
  topics: /ros2_cpu /cpu_stats /swarm/order /swarm_driver_cpu /swarm/status /driver_cpu /rviz2_cpu /webots_bin_cpu /dron01/local_pose /dron01/local_pose_gt /dron01/goal_pose /dron01/global_error /dron01/mr_data_gt /dron01/mr_data_gt_mod /dron01/mr_data /dron01/mr_data_mod /dron01/dron02/data /dron01/dron02/error /dron01/dron06/data /dron01/dron06/error /dron01/dron10/data /dron01/dron10/error /dron01/dron12/data /dron01/dron12/error /dron01/cone/data /dron01/cone/error /dron02/local_pose /dron02/local_pose_gt /dron02/goal_pose /dron02/global_error /dron02/mr_data_gt /dron02/mr_data_gt_mod /dron02/mr_data /dron02/mr_data_mod /dron02/dron01/data /dron02/dron01/error /dron02/dron03/data /dron02/dron03/error /dron02/dron07/data /dron02/dron07/error /dron02/dron12/data /dron02/dron12/error /dron02/cone/data /dron02/cone/error /dron03/local_pose /dron03/local_pose_gt /dron03/goal_pose /dron03/global_error /dron03/mr_data_gt /dron03/mr_data_gt_mod /dron03/mr_data /dron03/mr_data_mod /dron03/dron02/data /dron03/dron02/error /dron03/dron04/data /dron03/dron04/error /dron03/dron07/data /dron03/dron07/error /dron03/dron08/data /dron03/dron08/error /dron03/dron11/data /dron03/dron11/error /dron03/dron12/data /dron03/dron12/error /dron03/cone/data /dron03/cone/error /dron04/local_pose /dron04/local_pose_gt /dron04/goal_pose /dron04/global_error /dron04/mr_data_gt /dron04/mr_data_gt_mod /dron04/mr_data /dron04/mr_data_mod /dron04/dron03/data /dron04/dron03/error /dron04/dron05/data /dron04/dron05/error /dron04/dron08/data /dron04/dron08/error /dron04/dron11/data /dron04/dron11/error /dron04/cone/data /dron04/cone/error /dron05/local_pose /dron05/local_pose_gt /dron05/goal_pose /dron05/global_error /dron05/mr_data_gt /dron05/mr_data_gt_mod /dron05/mr_data /dron05/mr_data_mod /dron05/dron04/data /dron05/dron04/error /dron05/dron06/data /dron05/dron06/error /dron05/dron09/data /dron05/dron09/error /dron05/dron11/data /dron05/dron11/error /dron05/cone/data /dron05/cone/error /dron06/local_pose /dron06/local_pose_gt /dron06/goal_pose /dron06/global_error /dron06/mr_data_gt /dron06/mr_data_gt_mod /dron06/mr_data /dron06/mr_data_mod /dron06/dron01/data /dron06/dron01/error /dron06/dron05/data /dron06/dron05/error /dron06/dron09/data /dron06/dron09/error /dron06/dron10/data /dron06/dron10/error /dron06/dron11/data /dron06/dron11/error /dron06/dron12/data /dron06/dron12/error /dron06/cone/data /dron06/cone/error /dron07/local_pose /dron07/local_pose_gt /dron07/goal_pose /dron07/global_error /dron07/mr_data_gt /dron07/mr_data_gt_mod /dron07/mr_data /dron07/mr_data_mod /dron07/dron02/data /dron07/dron02/error /dron07/dron03/data /dron07/dron03/error /dron07/dron12/data /dron07/dron12/error /dron07/cone/data /dron07/cone/error /dron08/local_pose /dron08/local_pose_gt /dron08/goal_pose /dron08/global_error /dron08/mr_data_gt /dron08/mr_data_gt_mod /dron08/mr_data /dron08/mr_data_mod /dron08/dron03/data /dron08/dron03/error /dron08/dron04/data /dron08/dron04/error /dron08/dron11/data /dron08/dron11/error /dron08/cone/data /dron08/cone/error /dron09/local_pose /dron09/local_pose_gt /dron09/goal_pose /dron09/global_error /dron09/mr_data_gt /dron09/mr_data_gt_mod /dron09/mr_data /dron09/mr_data_mod /dron09/dron05/data /dron09/dron05/error /dron09/dron06/data /dron09/dron06/error /dron09/dron11/data /dron09/dron11/error /dron09/cone/data /dron09/cone/error /dron10/local_pose /dron10/local_pose_gt /dron10/goal_pose /dron10/global_error /dron10/mr_data_gt /dron10/mr_data_gt_mod /dron10/mr_data /dron10/mr_data_mod /dron10/dron01/data /dron10/dron01/error /dron10/dron06/data /dron10/dron06/error /dron10/dron12/data /dron10/dron12/error /dron10/cone/data /dron10/cone/error /dron11/local_pose /dron11/local_pose_gt /dron11/goal_pose /dron11/global_error /dron11/mr_data_gt /dron11/mr_data_gt_mod /dron11/mr_data /dron11/mr_data_mod /dron11/dron03/data /dron11/dron03/error /dron11/dron04/data /dron11/dron04/error /dron11/dron05/data /dron11/dron05/error /dron11/dron06/data /dron11/dron06/error /dron11/dron08/data /dron11/dron08/error /dron11/dron09/data /dron11/dron09/error /dron11/dron12/data /dron11/dron12/error /dron11/cone/data /dron11/cone/error /dron12/local_pose /dron12/local_pose_gt /dron12/goal_pose /dron12/global_error /dron12/mr_data_gt /dron12/mr_data_gt_mod /dron12/mr_data /dron12/mr_data_mod /dron12/dron01/data /dron12/dron01/error /dron12/dron02/data /dron12/dron02/error /dron12/dron03/data /dron12/dron03/error /dron12/dron06/data /dron12/dron06/error /dron12/dron07/data /dron12/dron07/error /dron12/dron10/data /dron12/dron10/error /dron12/dron11/data /dron12/dron11/error /dron12/cone/data /dron12/cone/error

Robots:
  Robot01:
    type: virtual
    name: dron01
    positioning: Intern
    pose: 0.44, 0.76, 0.70
    uri: radio://0/80/2M/E7E7E7E701
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron02_0.5, dron06_0.5, dron10_0.53846, dron12_0.99293, cone_0.5-1.4-0.0-0.0-0.6

  Robot02:
    type: virtual
    name: dron02
    positioning: Intern
    pose: -0.44, 0.76, 0.70
    uri: radio://0/80/2M/E7E7E7E702
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron01_0.5, dron03_0.5, dron07_0.49504, dron12_1.0146, cone_0.5-1.4-0.0-0.0-0.6

  Robot03:
    type: virtual
    name: dron03
    positioning: Intern
    pose: -0.88, 0.00, 0.70
    uri: radio://0/80/2M/E7E7E7E703
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron02_0.5, dron04_0.5005, dron07_0.64199, dron08_0.5381, dron11_1.0507, dron12_1.0912, cone_0.5-1.4-0.0-0.0-0.6

  Robot04:
    type: virtual
    name: dron04
    positioning: Intern
    pose: -0.44, -0.76, 0.70
    uri: radio://0/80/2M/E7E7E7E704
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron03_0.5005, dron05_0.5005, dron08_0.53864, dron11_0.99293, cone_0.5-1.4-0.0-0.0-0.6

  Robot05:
    type: virtual
    name: dron05
    positioning: Intern
    pose: 0.44, -0.76, 0.70
    uri: radio://0/80/2M/E7E7E7E705
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron04_0.5005, dron06_0.49899, dron09_0.49504, dron11_1.0146, cone_0.5-1.4-0.0-0.0-0.6

  Robot06:
    type: virtual
    name: dron06
    positioning: Intern
    pose: 0.88, -0.00, 0.70
    uri: radio://0/80/2M/E7E7E7E706
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron01_0.5, dron05_0.49899, dron09_0.64199, dron10_0.5381, dron11_1.0911, dron12_1.0506, cone_0.5-1.4-0.0-0.0-0.6

  Robot07:
    type: virtual
    name: dron07
    positioning: Intern
    pose: -0.29, 0.51, 1.28
    uri: radio://0/80/2M/E7E7E7E707
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron02_0.49504, dron03_0.64199, dron12_0.52696, cone_0.5-1.4-0.0-0.0-0.6

  Robot08:
    type: virtual
    name: dron08
    positioning: Intern
    pose: -0.51, -0.29, 1.28
    uri: radio://0/80/2M/E7E7E7E708
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron03_0.5381, dron04_0.53864, dron11_0.52705, cone_0.5-1.4-0.0-0.0-0.6

  Robot09:
    type: virtual
    name: dron09
    positioning: Intern
    pose: 0.29, -0.51, 1.28
    uri: radio://0/80/2M/E7E7E7E709
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron05_0.49504, dron06_0.64199, dron11_0.52688, cone_0.5-1.4-0.0-0.0-0.6

  Robot10:
    type: virtual
    name: dron10
    positioning: Intern
    pose: 0.51, 0.29, 1.28
    uri: radio://0/80/2M/E7E7E7E710
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron01_0.53846, dron06_0.5381, dron12_0.52696, cone_0.5-1.4-0.0-0.0-0.6

  Robot11:
    type: virtual
    name: dron11
    positioning: Intern
    pose: -0.08, -0.28, 1.87
    uri: radio://0/80/2M/E7E7E7E711
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron03_1.0507, dron04_0.99293, dron05_1.0146, dron06_1.0911, dron08_0.52705, dron09_0.52688, dron12_0.334, cone_0.5-1.4-0.0-0.0-0.6

  Robot12:
    type: virtual
    name: dron12
    positioning: Intern
    pose: 0.08, 0.28, 1.87
    uri: radio://0/80/2M/E7E7E7E712
    communication:
      type: Continuous
      threshold:
        type: Constant
        co: 0.01
        ai: 0.0
    local_pose:
      enable: True
      path: False
      T: 100
    local_twist:
      enable: False
      T: 20
    mars_data:
      enable: True
      T: 50
    task: 
      enable: True
      T: 100
      Onboard: True
      controller:
        type: ML2_v
        protocol: Continuous
        period: 0.2
        upperLimit: 0.3
        lowerLimit: -0.3
        gain: 0.25
        threshold:
            type: Constant
            co: 0.01
            ai: 0.0
      role: consensus
      type: distance
      relationship: dron01_0.99293, dron02_1.0146, dron03_1.0912, dron06_1.0506, dron07_0.52696, dron10_0.52696, dron11_0.334, cone_0.5-1.4-0.0-0.0-0.6

Supervisor:
  enable: True
  node: 
    executable: supervisor_node
    name: supervisor
    pkg: mars_supervisor_pkg
    file: LagrangeMultipliers_cone_N12_topics.yaml

Other:
  Agent00:
    enable: False