#!/usr/bin/env python3
"""Dev utility (not installed by the package) to generate experience
config/topics YAML files for the Herding-scalability and
Formaciones-Adaptativas experiments, from the existing, known-good
IROS_AffineFormation_config_N05.yaml as a structural template (same
Operation/Architecture/CPU_Monitoring/Interface/Data_Logging/Supervisor
schema, only Robots/world/rviz/Architecture.node change).

Run manually from this directory:
    python3 generate_experience_yaml.py
"""
import copy
import math
from pathlib import Path

import yaml

RES = Path(__file__).parent.parent / 'resources'
BASE = yaml.safe_load((RES / 'IROS_AffineFormation_config_N05.yaml').read_text())


def herder_robot(name, pose_xyz, neighbours, uri_suffix, role='herder', task_type='herding'):
    r = copy.deepcopy(BASE['Robots']['Robot01'])
    r['name'] = name
    r['pose'] = f"{pose_xyz[0]:.3f}, {pose_xyz[1]:.3f}, {pose_xyz[2]:.3f}"
    r['uri'] = f'radio://0/80/2M/E7E7E7E7{uri_suffix:02d}'
    r['role'] = role
    r['task']['role'] = role
    r['task']['type'] = task_type
    r['task']['relationship'] = neighbours
    return r


def khepera_robot(name, agent_ip):
    r = copy.deepcopy(BASE['Robots']['Robot06'])
    r['name'] = name
    r['agent_ip'] = agent_ip
    r['role'] = 'herd'
    return r


def write_yaml(doc, path):
    path.write_text(
        '# Auto-generated by scripts/generate_experience_yaml.py -- edit the '
        'script, not this file, to change the schema.\n' + yaml.dump(
            doc, sort_keys=False, default_flow_style=False))
    print(f"wrote {path}")


def herding_scale(N):
    doc = copy.deepcopy(BASE)
    doc['Operation']['world'] = f'Herding_N{N:02d}.wbt'
    doc['Interface']['rviz2']['file'] = f'Herding_N{N:02d}.rviz'
    per_dron = ' '.join(
        f'/dron{k + 1:02d}/local_pose /dron{k + 1:02d}/target_pose' for k in range(N))
    doc['Data_Logging']['topics'] = (
        '/current_theta /dist_sp /swarm/order /swarm/status ' + per_dron +
        ' /khepera01/local_pose /khepera01/target_pose /khepera01/goal_pose')

    robots = {}
    radius = 1.1
    for k in range(N):
        name = f'dron{k + 1:02d}'
        prev = f'dron{((k - 1) % N) + 1:02d}'
        nxt = f'dron{((k + 1) % N) + 1:02d}'
        a = 2 * math.pi * k / N
        pose = (radius * math.cos(a), radius * math.sin(a), 0.88)
        robots[f'Robot{k + 1:02d}'] = herder_robot(
            name, pose, f'{prev}_1.1756, {nxt}_1.1756, khepera_1.0', k + 1)
    robots[f'Robot{N + 1:02d}'] = khepera_robot('khepera01', '192.168.0.21')
    doc['Robots'] = robots
    return doc


def leader_or_follower_robot(name, role, pose_xyz, uri_suffix):
    r = copy.deepcopy(BASE['Robots']['Robot01'])  # mirrors the known-good per-robot block
    r['name'] = name
    r['pose'] = f"{pose_xyz[0]:.4f}, {pose_xyz[1]:.4f}, {pose_xyz[2]:.4f}"
    r['uri'] = f'radio://0/80/2M/E7E7E7E7{uri_suffix:02d}'
    r['role'] = role
    r['task']['role'] = role
    r['task']['type'] = 'triangulated_formation'
    r['task']['relationship'] = ''  # unused by triangulated_formation_node (mesh comes from Mesh:)
    return r


MESH = {
    1: (0.9000, 0.0000, 1.1000), 2: (1.2990, 0.7500, 0.3500),
    3: (0.4500, 0.7794, 1.1000), 4: (-0.4500, 0.7794, 1.1000),
    5: (-0.9000, 0.0000, 1.1000), 6: (-0.4500, -0.7794, 1.1000),
    7: (0.4500, -0.7794, 1.1000), 8: (0.0000, 1.5000, 0.3500),
    9: (-1.2990, 0.7500, 0.3500), 10: (-1.2990, -0.7500, 0.3500),
    11: (0.0000, -1.5000, 0.3500), 12: (1.2990, -0.7500, 0.3500),
}
TRIANGLES = [
    [1, 2, 3], [1, 2, 12], [1, 7, 12], [2, 3, 8], [3, 4, 8], [4, 5, 9],
    [4, 8, 9], [5, 6, 10], [5, 9, 10], [6, 7, 11], [6, 10, 11], [7, 11, 12],
]


def adaptive_formation(name_suffix, world, rviz, uncertainty_enable=False,
                        control_gain=4.0, robot_type='virtual'):
    doc = copy.deepcopy(BASE)
    doc['Operation']['world'] = world
    doc['Operation']['mode'] = 'virtual' if robot_type == 'virtual' else 'physical'
    doc['Experience']['type'] = 'formation'
    doc['Architecture']['node']['executable'] = 'triangulated_formation_node'
    doc['Interface']['rviz2']['file'] = rviz
    doc['Interface']['rqt']['file'] = 'IROS_Formation.perspective'
    per_dron = ' '.join(f'/dron{i:02d}/local_pose /dron{i:02d}/target_pose' for i in range(1, 13))
    doc['Data_Logging']['topics'] = (
        '/formation_error /formation_scale /swarm/order /swarm/status ' + per_dron)

    robots = {}
    for i in range(1, 13):
        role = 'leader' if i in (1, 2) else 'follower'
        r = leader_or_follower_robot(f'dron{i:02d}', role, MESH[i], i)
        r['type'] = robot_type
        robots[f'Robot{i:02d}'] = r
    doc['Robots'] = robots
    doc['Mesh'] = {'triangles': TRIANGLES}

    doc['Formation'] = {
        'control_gain': control_gain,
        'uncertainty_enable': uncertainty_enable,
    }
    doc['Supervisor']['node']['file'] = (
        'AdaptiveFormation_topics_reconfig.yaml' if 'reconfig' in name_suffix
        else 'AdaptiveFormation_topics_static.yaml')
    return doc


if __name__ == '__main__':
    for N in (7, 9, 13):
        write_yaml(herding_scale(N), RES / f'Herding_N{N:02d}_scale.yaml')

    write_yaml(
        adaptive_formation('static', 'AdaptiveFormation_N12.wbt', 'AdaptiveFormation_N12.rviz'),
        RES / 'AdaptiveFormation_N12_static.yaml')
    write_yaml(
        adaptive_formation('reconfig', 'AdaptiveFormation_N12.wbt', 'AdaptiveFormation_N12.rviz'),
        RES / 'AdaptiveFormation_N12_reconfig.yaml')
    write_yaml(
        adaptive_formation('uncertainty', 'AdaptiveFormation_N12.wbt',
                            'AdaptiveFormation_N12.rviz', uncertainty_enable=True),
        RES / 'AdaptiveFormation_N12_uncertainty.yaml')
    write_yaml(
        adaptive_formation('gainsweep', 'AdaptiveFormation_N12.wbt',
                            'AdaptiveFormation_N12.rviz', control_gain=1.0),
        RES / 'AdaptiveFormation_N12_gainsweep_low.yaml')
    write_yaml(
        adaptive_formation('static', 'AdaptiveFormation_N12.wbt', 'AdaptiveFormation_N12.rviz',
                            control_gain=4.0, robot_type='physical'),
        RES / 'AdaptiveFormation_N12_real.yaml')
